AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  LambdaetlcurrentdataFire:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 10240
      Timeout: 900
      Role: 'arn:aws:iam::489961935595:role/robomaker_students'
      Layers:
        - 'arn:aws:lambda:us-east-1:489961935595:layer:my_custom_lambda_layer:3'
